// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  form_section: dynamic(() => import("./FormSection")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  service: dynamic(() => import("./Service")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
